import Breadcrumb from '@/app/components/dashboard/breadcrumb';
import { PostField } from '@/app/lib/interface';
import AddPost from './add';
import EditPost from './edit';
import DeletePost from './delete';

const title = 'Posts';
const breadcrumbItems = [
  { text: 'Home', href: '/dashboard' },
  { text: title, href: '#' },
];

export const metadata = {
  title: 'Post',
  description: 'Generated by Post',
};

async function getPosts() {
  const pathUrl = '/posts';
  const fullUrl = process.env.DASHBOARD_BASE_URL_API + pathUrl;
  const response = await fetch(fullUrl, {
    cache: 'no-store',
  });
  return response.json();
}

export default async function Page() {
  let posts: PostField[] = [];

  try {
    posts = await getPosts();
  } catch (error) {
    console.error(error);
  }

  return (
    <>
      <div className="h-full">
        <div className="mb-2 rounded-md bg-gray-100 p-3 text-black">
          <div className="border-b-5 flex items-center">
            <div className="w-full">
              <h1 className="text-2xl">{title}</h1>
            </div>
            <div className="w-full">
              <Breadcrumb items={breadcrumbItems} />
            </div>
          </div>
        </div>
        <div className="min-h-max rounded-md bg-gray-100 p-3 text-black">
          <div className="flex w-full">
            <AddPost />
          </div>
          <div className="mt-3 w-full scroll-auto">
            <div className="relative overflow-x-auto">
              <table className="w-full text-left text-sm text-gray-500 rtl:text-right">
                <thead className="bg-gray-800 text-xs uppercase text-gray-50">
                  <tr>
                    <th scope="col" className="px-6 py-3">
                      #
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Title
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Body
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {posts.map((post) => (
                    <tr key={post._id} className="bg-whit border-b">
                      <td className="px-6 py-4">{post._id}</td>
                      <td className="px-6 py-4">{post.title}</td>
                      <td className="px-6 py-4">{post.body}</td>
                      <td className="flex px-6 py-4">
                        <div className="mr-1">
                          <EditPost {...post} />
                        </div>
                        <DeletePost {...post} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
