import Breadcrumb from '@/components/dashboard/breadcrumb';

const title = 'Home';
const breadcrumbItems = [{ text: title, href: '#' }];

export const metadata = {
  title: 'Home',
  description: 'Generated by Home',
};

export default async function Page() {
  return (
    <>
      <div className="min-h-full rounded-md bg-gray-100 p-4 text-black ">
        <div className="flex items-center border-b-4 border-indigo-500">
          <div className="w-full">
            <h1 className="text-2xl">{title}</h1>
          </div>
          <div className="w-full">
            <Breadcrumb items={breadcrumbItems} />
          </div>
        </div>
        <div className="mt-4 w-full">Content</div>
      </div>
    </>
  );
}
