import CardTodaySales from '@/components/dashboard/card-today-sales';
import CardWeeklySales from '@/components/dashboard/card-weekly-sales';
import CardSales from '@/components/dashboard/card-sales';
import CardProfit from '@/components/dashboard/card-profit';
import CardProductClass from '@/components/dashboard/card-product-class';
import HeadNav from '@/components/dashboard/headnav';
import CardRecentOrders from '@/components/dashboard/card-recent-orders';
import CardCustomerSatisfaction from '@/components/dashboard/card-customer-satisfaction';
import CardSalesTarget from '@/components/dashboard/card-sales-target';

// const breadcrumbItems = [{ text: title, href: '#' }];

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Dashboard',
};

export default async function Page() {
  return (
    <>
      <HeadNav title="Hello Gokul" subTitle="Welcome Back!" />
      <CardTodaySales />
      <div className="grid grid-cols-2 lg:grid-cols-2 xl:grid-cols-4 gap-4">
        <div className="col-span-2 lg:col-span-1">
          <CardWeeklySales />
        </div>
        <div className="col-span-1 md:col-span-2 lg:col-span-1">
          <CardSales />
        </div>
        <div className="col-span-1 md:col-span-2 lg:col-span-1">
          <CardProfit />
        </div>
        <div className="col-span-2 lg:col-span-1">
          <CardProductClass />
        </div>
        <div className="col-span-2 lg:col-span-1">
          <CardCustomerSatisfaction />
        </div>
        <div className="col-span-2 lg:col-span-2">
          <CardRecentOrders />
        </div>
        <div className="col-span-2 lg:col-span-1">
          <CardSalesTarget />
        </div>
      </div>
    </>
  );
}
