import CardTodaySales from '@/components/dashboard/card-today-sales';
import CardWeeklySales from '@/components/dashboard/card-weekly-sales';
import CardSales from '@/components/dashboard/card-sales';

const title = 'Dashboard';
const breadcrumbItems = [{ text: title, href: '#' }];

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Dashboard',
};

export default async function Page() {
  return (
    <>
      <CardTodaySales />
      <div className="flex md:flex md:flex-wrap gap-4">
        <div className="w-full min-w-fit md:w-1/4">
          <CardWeeklySales />
        </div>
        <div className="w-full lg:w-1/4">
          <CardSales />
        </div>
      </div>
    </>
  );
}
